name: my_dbt_project           
version: '2.0'                 

models:
  singlestore_dbt:
    schema: 'qa2_events'    
    # +materialized: table
    # +schema: '{{ env_var("SINGLESTORE_SCHEMA") }}'    



