name: "my_dbt_project"
version: "1.0"
config-version: 2

# Must match the top-level key in profiles.yml
profile: "singlestore_dbt"

# Where dbt looks for your .sql models
source-paths: ["models"]

# Where dbt writes compiled files & artifacts
target-path: "target"
clean-targets:
  - "target"

# Default materialization + (optional) schema override
models:
  my_dbt_project:
    +materialized: table
    # You *can* override schema here, but it’s usually better to let the profile control it:
    # +schema: "{{ env_var('SINGLESTORE_SCHEMA') }}"
