name: my_dbt_project           # already there
version: '2.0'                 # already there

# ← Add this line:
profile: singlestore           # ← must match a key in ~/.dbt/profiles.yml

config-version: 2              # or whatever your file has
# … the rest of your project config …
