singlestore_dbt:                 # ← matches profile: in dbt_project.yml :contentReference[oaicite:11]{index=11}
  target: dynamic                # The default target to use when you run `dbt run` :contentReference[oaicite:12]{index=12}
  outputs:
    dynamic:
      type: singlestore          # Use the dbt-singlestore adapter :contentReference[oaicite:13]{index=13}
      threads: 4                 # Number of concurrent threads for dbt :contentReference[oaicite:14]{index=14}
      host:     "{{ env_var('SINGLESTORE_HOST') }}"         # DB host, from env var :contentReference[oaicite:15]{index=15}
      port:     {{ env_var('SINGLESTORE_PORT', 3306) }}     # DB port, default 3306 :contentReference[oaicite:16]{index=16}
      user:     "{{ env_var('SINGLESTORE_USER') }}"         # DB username :contentReference[oaicite:17]{index=17}
      password: "{{ env_var('SINGLESTORE_PASSWORD') }}"     # DB password :contentReference[oaicite:18]{index=18}
      database: "{{ env_var('SINGLESTORE_DB') }}"           # Database name :contentReference[oaicite:19]{index=19}
      schema:   "{{ env_var('SINGLESTORE_SCHEMA', env_var('SINGLESTORE_DB')) }}"  
                                     # Schema/prefix for models :contentReference[oaicite:20]{index=20}
