singlestore:
  target: dev
  outputs:
    dev:
      type: singlestore
      host: 10.49.18.95
      port: 3306
      user: root
      password: Acres1234
      database: qa2_events
      schema: qa2_events
      threads: 4
# singlestore_dbt:
#   target: dynamic
#   outputs:
#     dynamic:
#       type: singlestore
#       threads: 1
#       host:     "{{ env_var('SINGLESTORE_HOST', 'localhost') }}"
#       port:     {{ env_var('SINGLESTORE_PORT', 3306) }}
#       user:     "{{ env_var('SINGLESTORE_USER', 'root') }}"
#       password: "{{ env_var('SINGLESTORE_PASSWORD', '') }}"
#       database: "{{ env_var('SINGLESTORE_DB', '') }}"
#       schema:   "{{ env_var('SINGLESTORE_SCHEMA', env_var('SINGLESTORE_DB')) }}"
