name: "my_dbt_project"           # The canonical name of your dbt project  
version: "1.0"                   # Semantic version of your project (optional in v1.5+)  
config-version: 2                # Use the v2 YAML syntax for configs :contentReference[oaicite:0]{index=0}

# Must match the key under profiles.yml
profile: "singlestore_dbt"       # Which profile dbt should load :contentReference[oaicite:1]{index=1}


# Default model configurations
models:
  my_dbt_project:                # Must match the `name:` above :contentReference[oaicite:5]{index=5}
    schema: 'qa2_events'